### ISSUE TITLE
cant view posts

### ISSUE THREAD

**Issue by glenfordwilliams** [shprink/wordpress-hybrid-client#111]
when i try to load the app nothing shows

GET http://www.dev.stlucianewsonline.com/wp-json/wp/v2/posts?_embed=true&filter…filter%5Borderby%5D=date&filter%5Bpost_status%5D=publish&page=1&per_page=5 404 (Not Found)

**Comment by shprink** [comment]
You clearly have a problem with WP-API

http://www.dev.stlucianewsonline.com/wp-json/wp/v2 should list all available routes.

Please try adding an issue on their github project: https://github.com/WP-API/WP-API

**Comment by ishanism** [comment]
I had this problem too.

This might be happening because, your rest-api is of version 1.x or  this(https://wordpress.org/plugins/json-rest-api/  this is found if you search for wp-api in wordpress). be sure it is to v2.0beta5(https://wordpress.org/plugins/rest-api/). also make sure that there are no two rest-api plugin activated together.

it should solve it.

**Comment by shprink** [comment]
You are right @ishanism both v1 and v2 together cannot work. It can be that :)

**Comment by glenfordwilliams** [comment]
i ended up removing json-rest-api but now im getting 

```
XMLHttpRequest cannot load http://www.dev.stlucianewsonline.com/wp-json/wp/v2/posts?_embed=true&filter…filter%5Borderby%5D=date&filter%5Bpost_status%5D=publish&page=1&per_page=5. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
```

**Comment by shprink** [comment]
Can't you see that http://www.dev.stlucianewsonline.com/wp-json/wp/v2 does not work? You should see a json not your blog page.

try disabling and re-enabling v2.

**Comment by glenfordwilliams** [comment]
already tried that but im still unable to get it to load. guess im gonna have to forget about using this project

**Comment by shprink** [comment]
create a ticket on WP-API project, the will help you. I would search around your .htaccess file.
